---
title: "Snakemake tutorial"
author: "Kristen Wells"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    highlight: "tango"
    df_print: "paged"
    self_contained: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = F,
  echo = T
)
```

Snakemake is a "tool to create reproducible and scalable data analysis". Snakemake is written in python and can be easily used on different servers and in different envrionments. I like it because it allows me to be confident that I am doing the exact same analysis on all samples and I can run through all steps of the analysis with one single submission script. It is also very easy to update between projects and you often need to edit just one configuration file.

## Installation

The recommendation is to install snakemake with conda. I've always just directly installed with conda

```{bash}
$ conda install -c bioconda -c conda-forge snakemake
``` 

Personally, I like to put conda into it's own environment so I run

```{bash}
$ conda create -n snakemake
$ conda activate snakemake
$ conda install -c bioconda -c conda-forge snakemake
```

If you do it this way, you will need to activate snakemake before running snakemake or submitting a script that runs snakemake.

```{bash}
$ conda activate snakemake
```

But the website actually recommends an additional step

```{bash}
$ conda install -c conda-forge mamba
$ mamba create -c conda-forge -c bioconda -n snakemake snakemake
```

Like my prefered method, this creates an environment for snakemake and you will need to activate the environment before running anything with snakemake

## Basic usage
To use snakemake you write "rules". These rules are individual steps of your analysis pipeline. For example for my RNA-seq analysis, I have a rule to run fastqc, a rule to make a summary of fastqc output, a rule to run star, a rule to make a summary of star output, a rule to run featureCounts, and a rule to make a count table. But let's start with a simple rule

### How to write a rule
Let's make a rule that will write the name of a sample to a file. To write the first rule, you need the following structure

```{python}
rule make_file:
    output:
        "results/first_file.txt"
    shell:
        """
        echo "this is a file" > {output}
        """
```

A few things to notice. 

1. You always need to name your rules (and the names need to be unique). 
2. You always need to have an output argument
3. You can run shell commands with the shell argument. If you run a shell command you need the three """ at the start and end of the command
4. You can directly call the output file without needing to 

How to write a rule

How to run just one rule

Write the rule in the tutorial
Write in a script that can be run

How to create a second rule

Write rule in tutorial
Write in script that can be run

How this second rule must relate to the first
	This will first check that the output from rule 1 is complete before running rule 2

How to see what will be run (-np)

Stringing rules together

How to run the rule for multiple samples (from the snake file)

Rule all

The config file

Reading from the config file into the snake file

Submitting the snakefile

Cleaning it up with multiple rule files