# The path to the data directory
DATA_PATH:
  /beevol/home/wellskri/Analysis/Tutorials/

# Sample names. These will be used for the output files
SAMPLES:
  - sample_28
  - sample_29
  - sample_30
  - sample_31

# Groups to use for paired samples. Must be a dictionary
GROUPS:
  group1:
    - sample_5
    - sample_6
  group2:
    - sample_7
    - sample_8