samples=["sample_1", "sample_2", "sample_3", "sample_4"]

rule all:
    input:
        # Create the fourth file for all samples
        expand(
            "results/{sample}_fourth_file.txt",
            sample = samples
        ),
        # Create the combined file from file two
        "results/combined_file.txt",
        # Create a file using params
        expand(
        	"results/{sample}_params_ex.txt",
        	sample = samples
        	)

include: "src/rules/first_rule.snake"
include: "src/rules/general_rule.snake"
include: "src/rules/rule_all_ex.snake"
include: "src/rules/rule_params_ex.snake"